[[guest]]
=== Guest execution

This method is recommended when patch testing is done automatically (i.e. through a 'cronjob'). However,
if you want to test your own patches, the <<host,host>> approach is a better option for making the code
cycle faster ('code-test-code').

NOTE: The following commands assumes that the 'patchtest/scripts' folder is visible on '$PATH'

* Create the guest machine, specifying the directory where the guest machine will be located

[source,shell]
----
create-guest-machine -g $HOME/patchtest-guest
----

* Create the share folder, containing the repositories needed by 'patchtest' inside the guest machine


[source,shell]
----
create-share-folder -s $HOME/patchtest-share
----

* Once the machine is created, there are two ways to launch the machine: manually or through a
crontab:

==== Manual ====


* Launch the guest machine through the 'guest' script

NOTE: This script does several tasks: 1. fetch latest series 2. pull relevant
repositories 3. launch the `core-image-patchtest` guest machine, the later
tests every patch found on '$HOME/patchtest-share/mboxes' then halt automatically; at host, the
results are located at '$HOME/patchtest-share/results'.

[source,shell]
----
guest -g $HOME/patchtest-guest -s $HOME/patchtest-share
----

* The later command can be executed anytime, testing latest series since last
time the command was executed. Consecutive 'guest' runs store the later data inside '$HOME/patchtest-share/backup' folder.

==== Crontab ====

* Set the correct share directory at '$HOME/patchtest-guest/cronenv'

NOTE: Network proxy env variables can also be included in this file.

[source,shell]
----
sed -i -e 's;SHAREDIR;$HOME/patchtest-share;' $HOME/patchtest-guest/cronenv
----

* Allow the cron user to run the following scripts with sudo permissions

[source,shell]
----
<cronjob-user> ALL=NOPASSWD: /home/<cron user>/patchtest-guest/poky/scripts/runqemu-ifup
<cronjob-user> ALL=NOPASSWD: /home/<cron user>/poky/scripts/runqemu-ifdown
----

* Set the crontab file

[source,shell]
----
crontab -u $USER $HOME/patchtest-guest/crontab
----

The cron will launch the 'scripts/guest' script every hour. The folders '$SHARE/mboxes' and '$SHARE/results'
contain previous patchtest input/output data. Consecutive crons backup the later data inside the
'$SHARE/backup' parent folder.

