[[guest]]
=== Guest execution

This method is recommended when patch testing is done automatically (i.e. through a 'cronjob'); however,
if you want to test your own patches, the <<host,host>> approach is a better option for making the code
cycle faster ('code-test-code').

NOTE: The code snipets shown below have been collected into a script 'scripts/create-guest'

* Clon patchtest and run the script 'scripts/create-guest', specifying a parent directory
where the guest machine will be located

[source,shell]
----
git://git.yoctoproject.org/patchtest
GUEST=$HOME/patchtest-guest
patchtest/scripts/create-guest -g $GUEST
----

* Once the machine is created, there are two ways to launch the machine: manually or through a
crontab:

==== Manual ====

[source,shell]
----
SHARE="<the folder to be share between host and guest, containing all data needed by patchtest inside guest>"
mkdir -p $SHARE
cd $SHARE
git clone git://git.yoctoproject.org/patchwork
git clone git://git.yoctoproject.org/patchtest
git clone git://git.yoctoproject.org/patchtest-oe
git clone git://git.openembedded.org/openembedded-core
git clone git://git.openembedded.org/bitbake openembedded-core/bitbake

cd $SHARE/openembedded-core
git config patchwork.default.url http://patchwork.openembedded.org
git config patchwork.default.project oe-core

rm -rf $GUEST/mboxes
fetch-mboxes -r $SHARE/openembedded-core -m $GUEST/mboxes

cd $GUEST/poky; . oe-init-build-env
KERNEL="$GUEST/poky/build/tmp/deploy/images/qemux86-64/bzImage-qemux86-64.bin"
ROOTFS="$GUEST/poky/build/tmp/deploy/images/qemux86-64/core-image-patchtest-qemux86-64.ext4"
runqemu \$KERNEL \$ROOTFS qemuparams="-snapshot -fsdev local,id=test_dev,path=$SHARE,security_model=mapped -device virtio-9p-pci,fsdev=test_dev,mount_tag=test_mount" nographic kvm
----

* Once launched, the virtual machine will automatically execute 'patchtest'

* Results are stored at $SHARE/results

All commands except cloning are required every time new series need to be tested.

==== Crontab ====

* Set the correct cron environment variables at '$GUEST/cronenv'; the later defined
the share folder ('$SHARE') and patchwork parameters (url, project and user credentials)
NOTE: Network proxy env variables can also be included in this file.

* Set the crontab file

[source,shell]
----
crontab -u $USER $GUESTDIR/crontab
----

The cron will launch the 'scripts/guest' script every hour. The folder '$SHARE/mboxes' and '$SHARE/results'
containg previous patchtest input/output data. Consecutive crons backup the later data inside the
'$SHARE/backup' parent folder, so no data is lost.


