[[scenarios]]
=== Secundary scripts and common scenarios

The script `patchtest` is the only script you would use in case you are testing a single
mbox and you do not really care about storing the results. These section cover others scripts,
secondary scripts, in the sense that these sit on top of `patchtest`,
that can help you the process of fetching mboxes from patchwork instance and/or
testing and collecting the results into repository.

NOTE: The following commands assumes that 'patchwork/git-pw', 'patchtest' and 'patchtest/scripts' folders are visible on '$PATH'

There are two main scripts

* 'fetch-mboxes': Fetch mboxes from a patchwork instance and place these into a output folder
* 'test-mboxes' : Test one or more mboxes, possible assembling these into into a git-branch and/or
                  storing results and logs into a target folder

[[fetching-mboxes]]
==== Fetching mboxes

In case you want want to fetch one ore more mboxes from a patchwork instance, you can do it in several ways:

Fetching a particular series/revision:

[source, shell]
----
git clone git://git.openembedded.org/openembedded-core
cd openembedded-core
git config patchwork.default.url http://patchwork.openembedded.org
git config patchwork.default.project 'oe-core'
fetch-mboxes -r <openembeded-core repo> 2017.1
----

In the above command, if no revision is provided (no `.1`), it will take the latest revision.

Fetching mboxes since a timestamp (and stored into a specific folder)

[source, shell]
----
fetch-mboxes -r <openembedded-core repo> -m $PWD/mboxes -s 2016-08-31
----

Or fetch latest mboxes since last git-pw poll

[source, shell]
----
fetch-mboxes -r <openembedded-core repo> -m $PWD/mboxes
----

This last command has a side-effect: it uses the `git-pw` tool to poll new events, so the later
updates the timestamp file ('$REPO/git-pw.<project>.poll.timestmap'). As a result, this tool
can be used to fetch new patches that have arrived to the mailing list through a cronjob as
describe in the <<guest, guest>> section.

WARNING: if the 'git-pw.<project>.poll.timestamp' file is not represent, it will poll events but will
not produce any mboxes. This avoids fetching many mboxes which may be not the desired behavior.

[[storing-results]]
==== Storing results

You may need to stored the results that the `patchtest` script yields. Let's say you have some
mboxes in a particular folder ('$PWD/mboxes') so you need to test them and store results into 'results'

[source,shell]
----
git clone git://git.openembedded.org/openembedded-core
git clone git://git.yoctoproject.org/patchtest-oe
test-mboxes -r $PWD/openembedded-core -s $PWD/patchtest-oe/tests -o $PWD/results $PWD/mboxes
----

The output directory 'results' contains raw patchtest results and logs.

[[assembling-mboxes]]
=== Assembling tested mboxes

Besides <<storing-results,storing results>>, one may be interested in assembling those patches
that have pass **all** tests into a particular branch:

[source,shell]
----
git clone git://git.openembedded.org/openembedded-core
git clone git://git.yoctoproject.org/patchtest-oe
test-mboxes -r $PWD/openembeded-core -s $PWD/patchtest-oe/tests -a patchtest-branch $PWD/mboxes
----

By default, the new branch created (`patchtest-branch` in this case) is checkout from `HEAD`, however one
can indicated another starting point with the parameter `-p`. If you want to merge the mboxes no matter
the test results, just include the parameter `-A` (inside the new branch, you will see some commits with
test failures). As in the `-o` case, the branch can be visited and commits review with standard
`git-log/show` where results are stored as `git-notes`.

