#!/bin/sh
#
# Script that sets the environment before running the guest script though
# GUESTDIR/crontab. The later crontab file is created with
# patchtest/scripts/create-guest script

SHARE="<SHARE>" # Share folder between host and guest, mboxes, repos and results are store here
PPWURL="https://patchwork.openembedded.org" # patchwork instance
PWPRO="oe-core" # patchwork project
PWUSER="" # patchwork username, required if results need to be posted
PWPASS="" # patchwork password, required if results need to be posted

