#!/bin/bash
# ex:ts=4:sw=4:sts=4:et
# -*- tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil -*-
#
# guest: fetch mboxes from patchwork at host and test them at
#        guest machine (qemu); once guest turns off, the host
#        post summary to the patchwork instance
#
# NOTE: This is script assumes that the user has already run the
#       create-share-folder and create-guest-machine scripts
#
# Copyright (C) 2016 Intel Corporation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Default values
SHAREDIR=''
GUESTDIR=''
POST=''
NOFETCH=''

function usage() {
    cat << EOF
\$ $(basename $0) [OPTION]

where OPTIONS are

    -s <share dir> : Share directory between host and guest
    -g <guest dir> : Guest directory where machine will be located
    -p             : Post results to the patchwork instance
    -n             : Do not fetch, just update repos and launch guest machine
EOF
>&2

    exit 1
}

while getopts ":s:g:pnh" opt; do
    case $opt in
	s)
	    SHAREDIR=$OPTARG
	    ;;
	g)
	    GUESTDIR=$OPTARG
	    ;;
	p)
	    POST='x'
	    ;;
	n)
	    NOFETCH='x'
	    ;;
	h)
	    usage
	    ;;
	\?)
	    echo "Invalid option: -$OPTARG" >&2
	    usage
	    ;;
	:)
	    echo "Option -$OPTARG requires an argument." >&2
	    usage
	    ;;
    esac
done

function pull() {
    local path=$1
    (
	cd $path
	git checkout master
	git pull
    )
}

function clean() {
    local path=$1
    (
	cd $path
	git am --abort
	git reset --hard
	git clean -f -e ".git-pw*"
    )
}

function test_network() {
    cd $OECORE
    git pw list -s `date --iso-8601` > /dev/null 2&>1
}

test -z "$SHAREDIR" && { echo "Provide the share directory folder created with create-share-folder script"; usage; }
test -z "$GUESTDIR" && { echo "Provide the guest directory folder created with create-guest-machine script"; usage; }

# make sure the poky build folder exists
test ! -d "$SHAREDIR" && { echo "Provide the share directory folder created with create-share-folder script"; usage; }
test ! -d "$GUESTDIR" && { echo "Provide the guest directory folder created with create-guest-machine script"; usage; }

SHAREDIR=$(readlink -e $SHAREDIR)
GUESTDIR=$(readlink -e $GUESTDIR)

# Define repo location and names
PW=$SHAREDIR/patchwork
PT=$SHAREDIR/patchtest
PTOE=$SHAREDIR/patchtest-oe
OECORE=$SHAREDIR/openembedded-core
BB=$OECORE/bitbake

test_network || { echo 'No network connection, quitting'; exit 1; }

# Clone or pull share repos
for repo in $PW $PT $PTOE $OECORE $BB; do
    clean $repo && pull $repo
done

if [ -z "$NOFETCH" ]; then
    # Get latest mboxes from the PW instance
    fetch-mboxes -r $OECORE -m $SHAREDIR/tmp/mboxes

    # if now new mboxes, just quit
    test ! -d $SHAREDIR/tmp/mboxes && { echo "Exiting"; exit 0; }

    # Check if old mboxes are present and backup these and its results
    # TODO: we must thing on something smarter to store past results
    # The first approach was the use of a git repository and git notes
    # but in this case a branch needs to be created in every run
    # and then use the post-summary script to get data from it.
    # A simpler approach is just storing plain texts and it is
    # the scripting does at the moment.
    if [ -d $SHAREDIR/mboxes ]; then

        # Unique folder to store previous mboxes/results
        now="$(date --iso-8601=minutes)"

        # Define and create unique backup dir
        backup="$SHAREDIR/backup/$now"
        test ! -d $backup && mkdir -p $backup

        # backup mboxes
        mv $SHAREDIR/mboxes $backup/mboxes

        # backup results (if exists)
        test -d $SHAREDIR/results && mv $SHAREDIR/results $backup/results
    fi

    # Move latest mboxes
    mv $SHAREDIR/tmp/mboxes $SHAREDIR/mboxes
fi

# launch qemu. Machine is assumed to be in the default build folder (build)
(
    if [ -d $GUESTDIR/poky ]; then
	cd $GUESTDIR/poky
    	if . oe-init-build-env build; then
    		runqemu qemux86-64 core-image-patchtest \
    			nographic kvm \
    			qemuparams="-snapshot \
				    -m 512 \
    	                            -fsdev local,id=test_dev,path=$SHAREDIR,security_model=mapped \
    	                            -device virtio-9p-pci,fsdev=test_dev,mount_tag=test_mount"
    	else
    		echo 'oe-init-build-env could not be sourced'
        fi
    else
	echo "Please run create-guest-machine -g $GUESTDIR"
	exit 1
    fi
)

# Post patchtest results ($SHAREDIR/results) into patchwork
if [ -n "$POST" ]; then
    post-summary -r $OECORE -R $SHAREDIR/results
fi
